[[servers]]
host = "172.27.72.4"
port = 389
use_ssl = false
start_tls = false
ssl_skip_verify = true
bind_dn = "dhsnext\\%s"
search_filter = "(sAMAccountName=%s)"
search_base_dns = ["dc=dhsnext,dc=nl"]

[servers.attributes]
name = "givenName"
surname = "sn"
username = "sAMAccountName"
member_of = "memberOf"
email =  "mail"

[[servers.group_mappings]]
group_dn = "cn=Administrators,cn=Builtin,dc=maf,dc=local"
org_role = "Admin"
grafana_admin = true