version: "3.4"

networks:
  net:
    driver: overlay
    attachable: true

volumes:
  guacdb:
    driver_opts:
      type: "nfs"
      o: "addr=172.27.72.20,nolock,rw"
      device: ":/mnt/POOL-01/DOCKERVOLS/guacdb"

services:
  postgres:
    image: postgres:11
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: P@ssword
      POSTGRES_USER: guacamole_user
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 128M
    volumes:
      - guacdb:/var/lib/postgresql
    networks:
      - net

  guacd:
    image: guacamole/guacd:1.1.0
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 128M
    networks:
      - net

  guac:
    image: guacamole/guacamole:1.1.0
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 128M
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: P@ssword
      POSTGRES_USER: guacamole_user
    networks:
      - net
    ports:
      - target: 8080
        published: 20080
        protocol: tcp
        mode: ingress