version: "3.4"

networks:
  net:
    driver: overlay
    attachable: true

volumes:
    nexus3:
      driver_opts:
        type: "nfs"
        o: "addr=172.27.72.20,nolock,rw"
        device: ":/mnt/POOL-01/DOCKERVOLS/nexus"

services:
  nexus:
    image: sonatype/nexus3:3.21.2
    volumes:
      - nexus3:/nexus-data
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: ingress
    networks:
      - net
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 1024M