version: '3.2'

services:
  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    configs:
      - source: endpoints
        target: /endpoints/endpoints.json
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "admin-password=$2y$05$9Vw9X2BC5sM5BRNZ8arAe.4FAoJk8Vxtjd9tQ/8sHEAQ30hdkcKuy"
        - "logo=https://img.maartenmol.nl/DHS_White%20zonder%20[Converted].png"
        - "external-endpoints=/endpoints/endpoints.json"

configs:
  endpoints:
    file: ./config/endpoints.json

networks:
  agent_network:
    driver: overlay
    attachable: true

volumes:
  portainer_data:
