version: '3.3'

services:
  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer
    command: --external-endpoints /endpoints/endpoints.json --logo "https://img.maartenmol.nl/DHS_White%20zonder%20[Converted].png" --admin-password '$$2y$$05$$9Vw9X2BC5sM5BRNZ8arAe.4FAoJk8Vxtjd9tQ/8sHEAQ30hdkcKuy'
    configs:
      - source: endpoints
        target: /endpoints/endpoints.json
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

configs:
  endpoints:
    file: ./config/endpoints.json

networks:
  agent_network:
    driver: overlay
    attachable: true

volumes:
  portainer_data:
