---
- hosts: docker_engine
  tasks:
    - name: Init a new swarm with default parameters
      delegate_to: docker-01
      docker_swarm:
        state: present
    - name: Ansible register Swarm Join Token for Worker
      delegate_to: docker-01
      shell: "docker swarm join-token worker -q"
      register: join_swarm_worker
    - name: Add nodes to new swarm
      delegate_to: "{{ item}}"
      with_items:
        - docker-02
        - docker-03
      docker_swarm:
        state: join
        advertise_addr: ""
        join_token: "{{ join_swarm_worker.stdout }}"
        remote_addrs: [ '172.27.72.61:2377' ]
- hosts: docker_swarm_manager
  tasks:
    - name: Deploy Portainer
      docker_stack:
        state: present
        name: portainer
        compose:
          - ~/dhs-config/infrastructure/3. Docker/portainer-agent-stack.yml